[loggers]
keys=root,uvicorn,uvicorn.access,uvicorn.error,sqlalchemy

[handlers]
keys=console,sqlfile,file

[formatters]
keys=uvicorn_timestamp_formatter

[formatter_uvicorn_timestamp_formatter]
format=%(asctime)s - [Backend] - %(levelname)s:    %(message)s
datefmt=%Y-%m-%d %H:%M:%S

[logger_root]
level=DEBUG
handlers=console,file

[logger_uvicorn]
level=INFO
handlers=console,file
qualname=uvicorn
propagate=0

[logger_uvicorn.access]
level=INFO
handlers=console,file
qualname=uvicorn.access
propagate=0

[logger_uvicorn.error]
level=INFO
handlers=console,file
qualname=uvicorn.error
propagate=0

[logger_sqlalchemy]
level=DEBUG
handlers=sqlfile
qualname=sqlalchemy.engine
propagate=0

[handler_console]
class=StreamHandler
level=INFO
# Use the uvicorn timestamp formatter for consistent console logs
formatter=uvicorn_timestamp_formatter
args=(sys.stderr,)

[handler_sqlfile]
class=FileHandler
level=DEBUG
# Use the uvicorn timestamp formatter for consistent SQL logs
formatter=uvicorn_timestamp_formatter
args=('../logs/sqlalchemy.log', 'a')

[handler_file]
# class=logging.handlers.RotatingFileHandler
# class=concurrent_log_handler.ConcurrentRotatingFileHandler <-- This is the fix
class=concurrent_log_handler.ConcurrentRotatingFileHandler
level=DEBUG
formatter=uvicorn_timestamp_formatter
args=('../logs/backend.log', 'a', 5242880, 3, 'utf-8')